name: Build


on:
  workflow_dispatch:
    inputs:
      name: 
        description: "Name please"
        default: "Arne Anka"
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v4
      
      - run: echo "Hello ${{ input.name }}"