name: Build

on:
  workflow_dispatch:
    inputs:
      name: 
        description: "Name please"
        default: "Arne Anka"
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ inputs.name }}"