name: Reusable workflow

on:
  workflow_call:
    inputs:
      name:
        description: 'Name for the job'
        required: true
        type: string
        default: 'World'

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v5
      - uses: ./simple-action
        id: greeting
        with:
          name: ${{ inputs.name }}
